---
name: bazzite-dawret
description: Personal bazzite image with Qemu and Hyprland

base-image: ghcr.io/ublue-os/bazzite
image-version: stable

modules:
  - type: dnf
    repos:
        copr:
          - name: lionheartp/Hyprland
    install:
      packages:
        - qemu-kvm
        - libvirt
        - virt-manager
        - edk2-ovmf
        - qemu
        - guestfs-tools

        - hyprland
        - xdg-desktop-portal-hyprland
        - waybar 
        - kitty
        - alacritty
        - ghostty
        - tailscale

  - type: systemd
    system:
      enabled:
        - libvirtd.service

